### ISSUE TITLE
Erreur avec Top Masteries

### ISSUE THREAD

**Issue by MBelangerB** [MBelangerB/BedyLeagueAPI#22]
URL : localhost:3000/lol/topMasteries/NA1/Bohe

Résultat :   { }

Erreur
```
Params: {"lang":"fr","region":"NA1","summonerName":"Bohe"}, Query string : 
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at new SummonerInfo (D:\_develop\API\BedyAPI\module\lol\summoner.js:31:32)
    at exports.topMasteries (D:\_develop\API\BedyAPI\routes\lol\summoner.js:105:23)
    at Layer.handle [as handle_request] (D:\_develop\API\BedyAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\_develop\API\BedyAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\_develop\API\BedyAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\_develop\API\BedyAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\_develop\API\BedyAPI\node_modules\express\lib\router\index.js:281:22
    at param (D:\_develop\API\BedyAPI\node_modules\express\lib\router\index.js:354:14)
    at param (D:\_develop\API\BedyAPI\node_modules\express\lib\router\index.js:365:14)
    at param (D:\_develop\API\BedyAPI\node_modules\express\lib\router\index.js:365:14)
[2022-08-16T00:06:43.100Z] GET /lol/topMasteries/NA1/Bohe 200 2 - 4.214 ms
```

**Comment by MBelangerB** [comment]
Fix,   le «queueType» n'étant pas défini avec TopMasteries ca faisait une erreur

`  if (this.queueType.toLowerCase() === "tft") {
                this.gameType = RequestManager.TokenType.TFT;
}`

Le code a été corrigé
  if (this.queueType?.toLowerCase() === "tft") {
                this.gameType = RequestManager.TokenType.TFT;
}
